[
    {
        "key": "dbln",
        "value": "%7B%2261575891482818%22%3A%2279CKWzog%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.184Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "datr",
        "value": "yKtRaHZ_ZWqRL1GBFgZziK3T",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "sb",
        "value": "yKtRaNfd1kPZJ9HbbAP0yI8O",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "c_user",
        "value": "61575891482818",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "xs",
        "value": "17%3AsY_pFGjgZSD_Cg%3A2%3A1750182906%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B698x360x2",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "fr",
        "value": "0VYQ1DaS9ZiN3Peqj.AWfDrHOsPw2vsLZ57aQTNh-nOzmC8q1In76yStG3mgkpJGWMgUM.BoUavI..AAA.0.0.BoUbjJ.AWekAI-HDC6Wc6L-s5bt9aUNHds",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "fbl_st",
        "value": "100639996%3BT%3A29169769",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2847%3Btimestamp%3A1750186185%3BCRCM%3A861517024",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-06-17T19:58:02.190Z",
        "lastAccessed": "2025-06-17T19:58:02.190Z"
    }
]
